import { ApplicationForm } from "@/components/application-form";
import { ChartCard } from "@/components/chart-card";
import { DataTable } from "@/components/data-table";
import { Input, Select, TextArea } from "@/components/forms";
import { PortalPage } from "@/components/portal-page";
import { Timeline } from "@/components/timeline";
import { UploadZone } from "@/components/upload-zone";
import { VideoInterviewPanel } from "@/components/video-interview-panel";
import { activityFeed, applicationTimeline, comparisonRows, jobs, pipelineRows, quickActions, reviewers } from "@/lib/data";
import { fetchMetrics } from "@/lib/api";
import { Role } from "@/lib/types";

function candidateContent(slug: string) {
  switch (slug) {
    case "profile":
      return { title: "Profile", description: "Maintain your details, experience, skills, and resume.", body: <section className="grid gap-6 xl:grid-cols-2"><div className="panel p-6"><h2 className="text-xl font-semibold text-ink">Personal information</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Input defaultValue="Ava" /><Input defaultValue="Morgan" /><Input defaultValue="ava@example.com" /><Input defaultValue="+94 77 123 4567" /></div><h3 className="mt-8 text-lg font-semibold text-ink">Skills</h3><div className="mt-4 flex flex-wrap gap-3">{["Product strategy", "Stakeholder management", "UX systems", "AI workflows"].map((skill) => <span key={skill} className="rounded-full bg-slate-100 px-4 py-2 text-sm text-slate-700">{skill}</span>)}</div></div><div className="panel p-6"><h2 className="text-xl font-semibold text-ink">Experience summary</h2><div className="mt-5 space-y-4"><TextArea defaultValue="Product leader with experience designing enterprise SaaS workflows and cross-functional operating models." /><TextArea defaultValue="Education: BSc in Information Systems. Experience: 6 years in product design and operations." /><button className="rounded-full bg-brand px-5 py-3 text-sm font-semibold text-white">Save profile</button></div></div></section> };
    case "apply":
      return { title: "CV Upload & Application", description: "Upload your resume, select a role, and submit supporting materials.", body: <section className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]"><UploadZone /><ApplicationForm /></section> };
    case "tracking":
      return { title: "Application Tracking", description: "Follow every stage of your application.", body: <section className="panel p-6"><Timeline items={applicationTimeline} /></section> };
    case "notifications":
      return { title: "Notifications", description: "Stay updated on interviews, status changes, and selection notices.", body: <section className="grid gap-4">{[["Interview invitation", "Senior Product Manager role interview scheduled for Mar 28 at 10:00 AM."],["Status update", "Your application has moved into hiring review."],["Selection notice", "You have been shortlisted for a final discussion."],["Physical interview", "Please confirm your on-site interview attendance."]].map(([title, body]) => <div key={title} className="panel p-6"><h2 className="text-lg font-semibold text-ink">{title}</h2><p className="mt-3 text-sm leading-7 text-muted">{body}</p></div>)}</section> };
    case "interviews":
      return { title: "Interview Schedule", description: "Review upcoming interviews and confirmation status.", body: <section className="grid gap-6 lg:grid-cols-3">{[["AI Interview", "Mar 27, 9:30 AM", "Online", "Confirmed"],["Hiring Panel", "Mar 30, 11:00 AM", "Video call", "Pending"],["Physical Interview", "Apr 02, 2:00 PM", "On-site", "Optional"]].map(([type, date, mode, status]) => <div key={type} className="panel p-6"><p className="text-sm text-muted">{type}</p><p className="mt-3 text-xl font-semibold text-ink">{date}</p><p className="mt-2 text-sm text-muted">{mode}</p><span className="mt-4 inline-flex rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-primary">{status}</span></div>)}</section> };
    case "ai-interview":
      return { title: "AI Interview", description: "Complete a distraction-free interview session.", body: <VideoInterviewPanel /> };
    default:
      return { title: "Welcome back, Ava", description: "Monitor applications, interviews, and profile readiness from one premium dashboard.", body: <section className="grid gap-6 xl:grid-cols-[0.95fr_1.05fr]"><div className="panel p-6"><h2 className="text-xl font-semibold text-ink">Application progress</h2><div className="mt-6"><Timeline items={applicationTimeline} /></div></div><div className="space-y-6"><ChartCard title="Profile readiness" subtitle="A strong profile improves job recommendations and screening accuracy." values={[{ label: "Resume completeness", value: 92 }, { label: "Skills alignment", value: 87 }, { label: "Portfolio quality", value: 84 }]} /><div className="panel p-6"><h2 className="text-xl font-semibold text-ink">Recommended jobs</h2><div className="mt-4 space-y-4">{jobs.slice(0, 3).map((job) => <div key={job.id} className="rounded-2xl bg-slate-50 p-4"><p className="font-semibold text-ink">{job.title}</p><p className="mt-2 text-sm text-muted">{job.summary}</p></div>)}</div></div></div></section> };
  }
}

function adminContent(slug: string) {
  switch (slug) {
    case "jobs":
      return { title: "Job Management", description: "Create, edit, archive, and manage openings.", body: <section className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><form className="panel p-6"><h2 className="text-xl font-semibold text-ink">Create or edit job</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Input placeholder="Role title" /><Input placeholder="Department" /><Input placeholder="Location" /><Select defaultValue="Active"><option>Active</option><option>Inactive</option><option>Archived</option></Select></div><div className="mt-4"><TextArea placeholder="Job summary, requirements, and AI scoring criteria" /></div><button className="mt-6 rounded-full bg-brand px-6 py-3 text-sm font-semibold text-white">Save job</button></form><DataTable headers={["Role", "Department", "Location", "Status"]} rows={jobs.map((job) => [job.title, job.department, job.location, job.status])} /></section> };
    case "candidates":
      return { title: "Candidate Management", description: "Review candidate records with search, sorting, AI scores, and fraud awareness.", body: <section className="space-y-6"><div className="grid gap-4 rounded-[2rem] border border-border bg-white p-4 md:grid-cols-4"><Input placeholder="Search candidate" /><Select defaultValue="All statuses"><option>All statuses</option><option>Shortlisted</option><option>Interviewed</option><option>Rejected</option></Select><Select defaultValue="Sort by score"><option>Sort by score</option><option>Match score</option><option>Fraud risk</option></Select><button className="rounded-2xl bg-brand px-4 py-3 text-sm font-semibold text-white">Apply</button></div><DataTable headers={["Candidate", "Role", "Match", "Soft Skills", "Ego", "Interview", "Fraud"]} rows={pipelineRows} /></section> };
    case "candidates/review":
      return { title: "Candidate Detail Review", description: "Inspect CV data, AI signals, interview evidence, and notes.", body: <section className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]"><div className="space-y-6"><div className="panel p-6"><h2 className="text-xl font-semibold text-ink">Candidate profile summary</h2><p className="mt-4 text-sm leading-7 text-muted">Meera Silva, AI Product Designer candidate with strong portfolio depth and high role-fit indicators.</p></div><div className="panel p-6"><h2 className="text-xl font-semibold text-ink">AI score breakdown</h2><div className="mt-4 space-y-3 text-sm text-muted"><p>Match score: 95%</p><p>Soft skills: 91%</p><p>Ego analysis: Low risk</p><p>Fraud detection: Low</p><p>Interview score: 90%</p></div></div></div><div className="grid gap-6"><div className="panel p-6"><h2 className="text-xl font-semibold text-ink">Structured CV</h2><p className="mt-4 text-sm leading-7 text-muted">8 years of product and design experience, led platform redesigns, and delivered enterprise dashboard systems.</p></div><div className="panel p-6"><h2 className="text-xl font-semibold text-ink">Interview responses & evidence</h2><p className="mt-4 text-sm leading-7 text-muted">Strong communication, clear tradeoff reasoning, and thoughtful collaboration examples. Video evidence available with synchronized question-answer logs.</p></div><div className="flex flex-wrap gap-3">{["Reject", "Shortlist", "Select", "Physical interview", "Direct join"].map((action) => <button key={action} className="rounded-full bg-brand px-5 py-3 text-sm font-semibold text-white">{action}</button>)}</div></div></section> };
    case "interviews":
      return { title: "Interview Management", description: "Reschedule interviews, track completion, and confirm readiness.", body: <section className="grid gap-6 lg:grid-cols-3">{[["Today", "12 interviews", "3 pending reschedules"],["AI completion", "91%", "Stable this week"],["Panel confirmations", "18", "6 awaiting reply"]].map(([title, value, note]) => <div key={title} className="panel p-6"><p className="text-sm text-muted">{title}</p><p className="mt-3 text-3xl font-semibold text-ink">{value}</p><p className="mt-2 text-sm text-muted">{note}</p></div>)}</section> };
    case "evidence":
      return { title: "Recording & Evidence Review", description: "Review interview video, logs, fraud screenshots, and behavior markers.", body: <VideoInterviewPanel /> };
    case "communications":
      return { title: "Communication Center", description: "Manage templates, message logs, and interview invitation flows.", body: <section className="grid gap-6 xl:grid-cols-[0.95fr_1.05fr]"><form className="panel p-6"><h2 className="text-xl font-semibold text-ink">Trigger communication</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Input placeholder="Candidate name" /><Select defaultValue="Select template"><option>Select template</option><option>Rejection email</option><option>Selection email</option><option>Physical interview invite</option></Select></div><div className="mt-4"><TextArea placeholder="Customize the message before sending" /></div><button className="mt-6 rounded-full bg-brand px-6 py-3 text-sm font-semibold text-white">Send communication</button></form><DataTable headers={["Recipient", "Template", "Status", "Time"]} rows={[["Meera Silva", "Selection email", "Sent", "09:42 AM"],["Ravi Jayasekara", "Rejection email", "Queued", "09:15 AM"],["Aisha Fernando", "Physical invite", "Delivered", "Yesterday"]]} /></section> };
    case "reports":
      return { title: "Reports & Analytics", description: "Analyze the hiring funnel, role performance, and interview completion trends.", body: <section className="grid gap-6 xl:grid-cols-2"><ChartCard title="Selection rate" subtitle="Selection efficiency by funnel stage." values={[{ label: "Engineering", value: 28 }, { label: "Product", value: 23 }, { label: "Operations", value: 19 }]} /><ChartCard title="Interview completion" subtitle="Completion rates for recent interview cohorts." values={[{ label: "AI interviews", value: 91 }, { label: "Panel interviews", value: 82 }, { label: "Physical interviews", value: 67 }]} /></section> };
    case "decisions":
      return { title: "Final Decision", description: "Compare shortlisted candidates and set final outcomes.", body: <section className="grid gap-6">{comparisonRows.map((candidate) => <div key={candidate.name} className="panel p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-xl font-semibold text-ink">{candidate.name}</h2><p className="mt-2 text-sm text-muted">{candidate.note}</p></div><div className="flex flex-wrap gap-4 text-sm text-muted"><span>Fit: {candidate.fit}</span><span>Interview: {candidate.interview}</span><span>Soft skills: {candidate.soft}</span><span>Fraud: {candidate.fraud}</span></div></div><div className="mt-5 flex flex-wrap gap-3">{["Rejected", "Shortlisted", "Selected", "Physical interview required", "Direct join"].map((action) => <button key={action} className="rounded-full bg-brand px-5 py-3 text-sm font-semibold text-white">{action}</button>)}</div></div>)}</section> };
    case "settings":
      return { title: "Settings", description: "Manage profile settings, preferences, notifications, and access.", body: <section className="grid gap-6 xl:grid-cols-2"><div className="panel p-6"><h2 className="text-xl font-semibold text-ink">Profile settings</h2><div className="mt-5 space-y-4"><Input defaultValue="Ava Morgan" /><Input defaultValue="ava@aihireagent.com" /></div></div><div className="panel p-6"><h2 className="text-xl font-semibold text-ink">System preferences</h2><div className="mt-5 space-y-4"><Select defaultValue="Email and in-app"><option>Email and in-app</option><option>In-app only</option><option>Email only</option></Select><Select defaultValue="White-first premium"><option>White-first premium</option><option>System default</option></Select></div></div></section> };
    default:
      return { title: "Admin Dashboard", description: "Track jobs, candidates, interview completion, fraud alerts, and workflow health.", body: <section className="grid gap-6 xl:grid-cols-[1fr_0.9fr]"><div className="grid gap-6"><ChartCard title="Hiring funnel" subtitle="Track progression from application through final decision." values={[{ label: "Applied", value: 100 }, { label: "Shortlisted", value: 61 }, { label: "Interviewed", value: 42 }, { label: "Selected", value: 18 }]} /><div className="panel p-6"><h2 className="text-xl font-semibold text-ink">Quick actions</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{quickActions.map((action) => <div key={action.title} className="rounded-2xl bg-slate-50 p-4"><p className="font-semibold text-ink">{action.title}</p><p className="mt-2 text-sm leading-6 text-muted">{action.detail}</p></div>)}</div></div></div><div className="panel p-6"><h2 className="text-xl font-semibold text-ink">Live activity</h2><div className="mt-4 space-y-4">{activityFeed.map((item) => <div key={item} className="rounded-2xl border border-border p-4 text-sm leading-6 text-muted">{item}</div>)}</div></div></section> };
  }
}

function hiringContent(slug: string) {
  switch (slug) {
    case "shortlisted":
      return { title: "Shortlisted Candidates", description: "Review AI results and add recommendations for shortlisted applicants.", body: <DataTable headers={["Candidate", "Role", "Match", "Soft Skills", "Ego", "Interview", "Fraud"]} rows={pipelineRows.slice(0, 3)} /> };
    case "interviews":
      return { title: "Interview Review", description: "Watch recordings, inspect answers, and review AI-generated insights.", body: <VideoInterviewPanel /> };
    case "comparison":
      return { title: "Candidate Comparison", description: "Compare shortlisted candidates side by side.", body: <section className="grid gap-6 xl:grid-cols-3">{comparisonRows.map((candidate) => <div key={candidate.name} className="panel p-6"><h2 className="text-xl font-semibold text-ink">{candidate.name}</h2><div className="mt-5 space-y-3 text-sm text-muted"><p>Role fit: {candidate.fit}</p><p>Interview: {candidate.interview}</p><p>Soft skills: {candidate.soft}</p><p>Fraud: {candidate.fraud}</p></div><p className="mt-4 text-sm leading-6 text-muted">{candidate.note}</p></div>)}</section> };
    case "collaboration":
      return { title: "Decision Collaboration", description: "Share reviewer notes and move candidates toward final review.", body: <section className="grid gap-6 lg:grid-cols-3">{reviewers.map((reviewer) => <div key={reviewer.name} className="panel p-6"><h2 className="text-lg font-semibold text-ink">{reviewer.name}</h2><p className="mt-2 text-sm text-muted">{reviewer.role}</p><p className="mt-4 text-sm leading-6 text-muted">{reviewer.note}</p><span className="mt-4 inline-flex rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-primary">{reviewer.status}</span></div>)}</section> };
    default:
      return { title: "Hiring Dashboard", description: "Access assigned roles, shortlisted candidates, and review tasks.", body: <section className="grid gap-6 xl:grid-cols-[1fr_0.9fr]"><ChartCard title="Assigned role load" subtitle="Current review capacity across your queue." values={[{ label: "Engineering", value: 82 }, { label: "Product", value: 66 }, { label: "Operations", value: 44 }]} /><div className="panel p-6"><h2 className="text-xl font-semibold text-ink">Reviewer pulse</h2><div className="mt-4 space-y-4">{reviewers.map((reviewer) => <div key={reviewer.name} className="rounded-2xl border border-border p-4"><p className="font-semibold text-ink">{reviewer.name}</p><p className="mt-1 text-sm text-muted">{reviewer.role}</p><p className="mt-2 text-sm text-primary">{reviewer.status}</p></div>)}</div></div></section> };
  }
}

export async function PortalContent({ role, slug }: { role: Role; slug: string }) {
  const metrics = await fetchMetrics(role);
  const content = role === "candidate" ? candidateContent(slug) : role === "admin" ? adminContent(slug) : hiringContent(slug);
  return <PortalPage role={role} title={content.title} description={content.description} metrics={metrics}>{content.body}</PortalPage>;
}